### ISSUE TITLE
Server crashes when fail to connect to Kaldi

### ISSUE THREAD

**Issue by andrenatal** [mozilla/vaani.server#1]
@tilmankamp The server is crashing with the following error when fails to connect to Kaldi. That's the expected behavior?

```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 52.37.26.79:8888
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! vaani.server@0.0.1 start: `./run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vaani.server@0.0.1 start script './run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vaani.server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./run
npm ERR! You can get their info via:
npm ERR!     npm owner ls vaani.server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anatal/projects/mozilla/vaani-iot/vaani.server/npm-debug.log
```

**Comment by tilmankamp** [comment]
Fixed by https://github.com/mozilla/vaani.server/commit/e80f3d53fb902a8adadfe7817674cc33a91b4dff .
