### ISSUE TITLE
Restart due to unhandled error event

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.server#15]
Sometimes the server is restarted due to an exception about an unhandled stream error.

``` sh
Sending answer: 0 - Added hi to your shopping list.
Sending answer: 0 - Added milk to your shopping list.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:152:17)
    at BufferReadable.Readable.push (_stream_readable.js:130:10)
    at BufferReadable._send (/var/app/current/lib/buffer/index.js:26:16)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
starting server...
```

**Comment by kdavis-mozilla** [comment]
Idea: Implement `BufferReadable` as a "pass-through" `Transform` `Stream`

**Comment by kdavis-mozilla** [comment]
@tilmankamp Can you redeploy the google server to test if this fix gets rid of the unhandled error?

**Comment by kdavis-mozilla** [comment]
@tilmankamp @andrenatal Created a new test ebs server in Frankfurt and ran it using this code testing by adding 50 items to my list. There was no hang due to this problem in the 50 trials.

So it seems as if this is solved. :-)
